# Generated by Django 5.1.1 on 2024-09-26 12:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("setting", "0005_alter_datasource_url"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatInfo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid1,
                        primary_key=True,
                        serialize=False,
                        verbose_name="会话 id",
                    ),
                ),
                ("user_demand", models.TextField(verbose_name="用户需求")),
                ("chat_content", models.JSONField(verbose_name="会话内容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "datasource_id",
                    models.ForeignKey(
                        db_column="datasource_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="setting.datasource",
                        verbose_name="数据源 id",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.user",
                        verbose_name="用户 id",
                    ),
                ),
            ],
            options={
                "verbose_name": "会话信息",
                "verbose_name_plural": "会话信息",
                "db_table": "chat_info",
            },
        ),
    ]
