# Generated by Django 5.1.1 on 2024-09-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatinfo",
            name="chat_content",
            field=models.JSONField(blank=True, null=True, verbose_name="会话内容"),
        ),
        migrations.AlterField(
            model_name="chatinfo",
            name="user_demand",
            field=models.TextField(blank=True, null=True, verbose_name="用户需求"),
        ),
    ]
