# Generated by Django 5.1.1 on 2024-10-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_alter_chatinfo_chat_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatinfo",
            name="sse_message_list",
            field=models.JSONField(blank=True, null=True, verbose_name="sse 消息列表"),
        ),
    ]
