# Generated by Django 5.1.1 on 2024-09-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="主键id"
                    ),
                ),
                (
                    "nick_name",
                    models.CharField(default="", max_length=150, verbose_name="昵称"),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="用户名"
                    ),
                ),
                ("password", models.CharField(max_length=150, verbose_name="密码")),
                ("role", models.CharField(max_length=150, verbose_name="角色")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="修改时间"
                    ),
                ),
            ],
            options={
                "db_table": "user",
            },
        ),
    ]
