# Generated by Django 5.1.1 on 2024-09-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_rename_nick_name_user_nickname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=102400, verbose_name="密码"),
        ),
    ]
