# Generated by Django 5.1.1 on 2024-09-23 08:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Datasource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="主键id"
                    ),
                ),
                (
                    "datasource_name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="数据源名称"
                    ),
                ),
                (
                    "datasource_description",
                    models.TextField(
                        blank=True,
                        default="",
                        max_length=1024,
                        null=True,
                        verbose_name="数据源描述",
                    ),
                ),
                (
                    "database_name",
                    models.CharField(max_length=255, verbose_name="数据库名称"),
                ),
                ("url", models.URLField(verbose_name="数据库地址")),
                ("port", models.IntegerField(verbose_name="端口")),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="用户名"
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="密码"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.user",
                        verbose_name="创建人",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Model",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="主键id"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="模型名称")),
                (
                    "model_name",
                    models.CharField(max_length=255, verbose_name="模型名称"),
                ),
                ("provider", models.CharField(max_length=255, verbose_name="提供商")),
                ("api_key", models.CharField(max_length=255, verbose_name="api key")),
                (
                    "base_url",
                    models.URLField(blank=True, null=True, verbose_name="base url"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.user",
                        verbose_name="创建人",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TableInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="主键id"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="表名")),
                ("ddl", models.TextField(verbose_name="表结构")),
                ("summary", models.TextField(verbose_name="表描述")),
                (
                    "datasource_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="setting.datasource",
                        verbose_name="数据源",
                    ),
                ),
            ],
        ),
    ]
