# Generated by Django 5.1.1 on 2024-09-23 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("setting", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="model",
            unique_together={("name", "created_by")},
        ),
        migrations.AlterUniqueTogether(
            name="tableinfo",
            unique_together={("name", "datasource_id")},
        ),
        migrations.AlterModelTable(
            name="datasource",
            table="datasource",
        ),
        migrations.AlterModelTable(
            name="model",
            table="model",
        ),
        migrations.AlterModelTable(
            name="tableinfo",
            table="table_info",
        ),
    ]
