# Generated by Django 5.1.1 on 2024-09-24 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setting", "0002_alter_model_unique_together_and_more"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="model",
            name="created_by",
            field=models.ForeignKey(
                db_column="created_by",
                on_delete=django.db.models.deletion.CASCADE,
                to="user.user",
                verbose_name="创建人",
            ),
        ),
    ]
