# Generated by Django 5.1.1 on 2024-09-25 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setting", "0003_alter_model_created_at_alter_model_created_by"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasource",
            name="created_by",
            field=models.ForeignKey(
                db_column="created_by",
                on_delete=django.db.models.deletion.CASCADE,
                to="user.user",
                verbose_name="创建人",
            ),
        ),
        migrations.AlterField(
            model_name="tableinfo",
            name="datasource_id",
            field=models.ForeignKey(
                db_column="datasource_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="setting.datasource",
                verbose_name="数据源",
            ),
        ),
    ]
