# Generated by Django 5.1.1 on 2024-09-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setting", "0004_alter_datasource_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasource",
            name="url",
            field=models.CharField(max_length=255, verbose_name="数据库地址"),
        ),
    ]
