# Generated by Django 5.1.1 on 2024-09-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setting", "0005_alter_datasource_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "type",
                    models.IntegerField(
                        choices=[(0, "私钥秘钥")],
                        primary_key=True,
                        serialize=False,
                        verbose_name="设置类型",
                    ),
                ),
                ("meta", models.JSONField(default=dict, verbose_name="配置数据")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
            ],
            options={
                "db_table": "system_setting",
            },
        ),
        migrations.AlterField(
            model_name="datasource",
            name="password",
            field=models.CharField(
                blank=True, max_length=102400, null=True, verbose_name="密码"
            ),
        ),
        migrations.AlterField(
            model_name="datasource",
            name="url",
            field=models.CharField(max_length=102400, verbose_name="数据库地址"),
        ),
        migrations.AlterField(
            model_name="model",
            name="api_key",
            field=models.CharField(max_length=102400, verbose_name="api key"),
        ),
    ]
