# Generated by Django 5.1.1 on 2024-09-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setting", "0006_systemsetting_alter_datasource_password_and_more"),
        ("user", "0003_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasource",
            name="datasource_name",
            field=models.CharField(max_length=255, verbose_name="数据源名称"),
        ),
        migrations.AlterUniqueTogether(
            name="datasource",
            unique_together={("datasource_name", "created_by")},
        ),
    ]
