# Generated by Django 5.1.1 on 2024-10-12 12:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationChatInfo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid1,
                        primary_key=True,
                        serialize=False,
                        verbose_name="会话 id",
                    ),
                ),
                ("user_demand", models.TextField(verbose_name="用户需求")),
                (
                    "chat_content",
                    models.JSONField(blank=True, null=True, verbose_name="会话内容"),
                ),
                (
                    "sse_message_list",
                    models.JSONField(
                        blank=True, null=True, verbose_name="sse 消息列表"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "db_table": "application_chat_info",
            },
        ),
    ]
